apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pg-upgrade
  name: pg-upgrade
  namespace: elektra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-upgrade
  template:
    metadata:
      labels:
        app: pg-upgrade
    spec:
      containers:
        - image: keppel.eu-de-1.cloud.sap/ccloud/elektra-pg-upgrade:latest
          imagePullPolicy: Always
          name: pg-upgrade
          securityContext:
            runAsUser: 0
          # TODO: remove next two lines
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          env:
            - name: NAME
              value: pg-upgrade
            - name: PG_VERSION
              value: "9.5"
            - name: INGRESS_NAME
              value: elektra
            - name: PG_DEPLOYMENT_NAME
              value: elektra-postgresql
            - name: PG_PVC_NAME
              value: elektra-postgresql
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              protocol: TCP

---
# https://jeremievallee.com/2018/05/28/kubernetes-rbac-namespace-user.html
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: elektra
  name: pg-upgrade
rules:
  - apiGroups: ["", "*", "apps"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]

---
# PERMISSIONS to use kubectl within the container
# I guess this needs to be adjusted ;-)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg-upgrade
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: elektra
roleRef:
  kind: Role
  name: pg-upgrade
  apiGroup: rbac.authorization.k8s.io
